In [1]:
import pandas as pd

In [ ]:
pd.read_csv(r"C:/path-to-file/etch_roof.csv")

In [ ]:
vCmass = 8.7 * 10 ** -3
vCmol_mass = (6*12.01 + 8*1.008 + 6*15.999)

vCmoles = vCmass/vCmol_mass
NvC = vCmoles * N_A
N_Carbon = 6 * NvC
NC14 = N_Carbon*N_Abundance

In [2]:
import numpy as np

In [4]:
my_data = np.array([1.2,2.3,3.4,1.5,np.nan])

In [5]:
my_data

array([1.2, 2.3, 3.4, 1.5, nan])

In [11]:
np.isnan(my_data)

array([False, False, False, False,  True])

In [17]:
my_data[~np.isnan(my_data)]

array([1.2, 2.3, 3.4, 1.5])